{"@t":"2023-03-03T23:41:19.8973598Z","@mt":"Registered 4 endpoints in 427 milliseconds.","SourceContext":"FastEndpoints.StartupTimer","Application":"auth-service"}
{"@t":"2023-03-03T23:41:20.0043596Z","@mt":"No validators found in the system!","SourceContext":"FastEndpoints.Swagger.ValidationSchemaProcessor","Application":"auth-service"}
{"@t":"2023-03-03T23:41:24.5816695Z","@mt":"An error occurred during migration","@l":"Error","@x":"Npgsql.NpgsqlException (0x80004005): Failed to connect to 127.0.0.1:5432\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\r\n   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)\r\n   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|208_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)\r\n   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.UnpooledDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)\r\n   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)\r\n   at Program.<Main>$(String[] args) in C:\\Users\\jenki\\source\\app\\solar-engineer\\src\\Services\\Auth.API\\Program.cs:line 71","SourceContext":"Program","Application":"auth-service","ExceptionDetail":{"HResult":-2147467259,"Message":"Failed to connect to 127.0.0.1:5432","Source":"Npgsql","TargetSite":"Void MoveNext()","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"IsTransient":true,"BatchCommand":null,"SqlState":null,"DbException.BatchCommand":null,"ErrorCode":-2147467259,"Type":"Npgsql.NpgsqlException"}}
{"@t":"2023-03-03T23:41:24.6973751Z","@mt":"Now listening on: {address}","address":"http://localhost:5005","EventId":{"Id":14,"Name":"ListeningOnAddress"},"SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:41:24.6982927Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:41:24.6983649Z","@mt":"Hosting environment: {EnvName}","EnvName":"Development","SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:41:24.6983975Z","@mt":"Content root path: {ContentRoot}","ContentRoot":"C:\\Users\\jenki\\source\\app\\solar-engineer\\src\\Services\\Auth.API","SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:41:28.7013762Z","@mt":"Connection Failed: {InputAddress}","@l":"Warning","@x":"RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable\r\n ---> System.AggregateException: One or more errors occurred. (Connection failed)\r\n ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)\r\n--- End of stack trace from previous location ---\r\n   at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)\r\n   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, ArrayPool`1 pool, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 hostnames, String clientProvidedName)\r\n   at MassTransit.RabbitMqTransport.ConnectionContextFactory.CreateConnection(ISupervisor supervisor) in /_/src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/ConnectionContextFactory.cs:line 86","InputAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"auth-service","ExceptionDetail":{"HResult":-2146232800,"Message":"None of the specified endpoints were reachable","Source":"RabbitMQ.Client","TargetSite":"RabbitMQ.Client.IConnection CreateConnection(RabbitMQ.Client.IEndpointResolver, System.String)","InnerException":{"Type":"System.AggregateException","HResult":-2146233088,"Message":"One or more errors occurred. (Connection failed)","Source":"RabbitMQ.Client","TargetSite":"T SelectOne[T](RabbitMQ.Client.IEndpointResolver, System.Func`2[RabbitMQ.Client.AmqpTcpEndpoint,T])","InnerException":{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"},"InnerExceptions":[{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"}]},"Type":"RabbitMQ.Client.Exceptions.BrokerUnreachableException"}}
{"@t":"2023-03-03T23:48:54.8605961Z","@mt":"Registered 4 endpoints in 218 milliseconds.","SourceContext":"FastEndpoints.StartupTimer","Application":"auth-service"}
{"@t":"2023-03-03T23:48:54.9230872Z","@mt":"No validators found in the system!","SourceContext":"FastEndpoints.Swagger.ValidationSchemaProcessor","Application":"auth-service"}
{"@t":"2023-03-03T23:48:59.5056214Z","@mt":"An error occurred during migration","@l":"Error","@x":"Npgsql.NpgsqlException (0x80004005): Failed to connect to 127.0.0.1:5432\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\r\n   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)\r\n   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)\r\n   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|208_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)\r\n   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.UnpooledDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|45_0(Boolean async, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)\r\n   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)\r\n   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)\r\n   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)\r\n   at Program.<Main>$(String[] args) in C:\\Users\\jenki\\source\\app\\solar-engineer\\src\\Services\\Auth.API\\Program.cs:line 71","SourceContext":"Program","Application":"auth-service","ExceptionDetail":{"HResult":-2147467259,"Message":"Failed to connect to 127.0.0.1:5432","Source":"Npgsql","TargetSite":"Void MoveNext()","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"IsTransient":true,"BatchCommand":null,"SqlState":null,"DbException.BatchCommand":null,"ErrorCode":-2147467259,"Type":"Npgsql.NpgsqlException"}}
{"@t":"2023-03-03T23:48:59.5847957Z","@mt":"Now listening on: {address}","address":"http://localhost:5005","EventId":{"Id":14,"Name":"ListeningOnAddress"},"SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:48:59.5856988Z","@mt":"Application started. Press Ctrl+C to shut down.","SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:48:59.5857847Z","@mt":"Hosting environment: {EnvName}","EnvName":"Development","SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:48:59.5858328Z","@mt":"Content root path: {ContentRoot}","ContentRoot":"C:\\Users\\jenki\\source\\app\\solar-engineer\\src\\Services\\Auth.API","SourceContext":"Microsoft.Hosting.Lifetime","Application":"auth-service"}
{"@t":"2023-03-03T23:49:03.6251530Z","@mt":"Connection Failed: {InputAddress}","@l":"Warning","@x":"RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable\r\n ---> System.AggregateException: One or more errors occurred. (Connection failed)\r\n ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)\r\n--- End of stack trace from previous location ---\r\n   at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)\r\n   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, ArrayPool`1 pool, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 hostnames, String clientProvidedName)\r\n   at MassTransit.RabbitMqTransport.ConnectionContextFactory.CreateConnection(ISupervisor supervisor) in /_/src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/ConnectionContextFactory.cs:line 86","InputAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"auth-service","ExceptionDetail":{"HResult":-2146232800,"Message":"None of the specified endpoints were reachable","Source":"RabbitMQ.Client","TargetSite":"RabbitMQ.Client.IConnection CreateConnection(RabbitMQ.Client.IEndpointResolver, System.String)","InnerException":{"Type":"System.AggregateException","HResult":-2146233088,"Message":"One or more errors occurred. (Connection failed)","Source":"RabbitMQ.Client","TargetSite":"T SelectOne[T](RabbitMQ.Client.IEndpointResolver, System.Func`2[RabbitMQ.Client.AmqpTcpEndpoint,T])","InnerException":{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"},"InnerExceptions":[{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"}]},"Type":"RabbitMQ.Client.Exceptions.BrokerUnreachableException"}}
{"@t":"2023-03-03T23:49:15.3027185Z","@mt":"Connection Failed: {InputAddress}","@l":"Warning","@x":"RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable\r\n ---> System.AggregateException: One or more errors occurred. (Connection failed)\r\n ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed\r\n ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\r\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\r\n   at System.Threading.Tasks.ValueTask.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)\r\n--- End of stack trace from previous location ---\r\n   at RabbitMQ.Client.Impl.TcpClientAdapter.ConnectAsync(String host, Int32 port)\r\n   at RabbitMQ.Client.Impl.TaskExtensions.TimeoutAfter(Task task, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectOrFail(ITcpClient socket, AmqpTcpEndpoint endpoint, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingAddressFamily(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout, AddressFamily family)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler.ConnectUsingIPv4(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan timeout)\r\n   at RabbitMQ.Client.Impl.SocketFrameHandler..ctor(AmqpTcpEndpoint endpoint, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.Framing.Impl.IProtocolExtensions.CreateFrameHandler(IProtocol protocol, AmqpTcpEndpoint endpoint, ArrayPool`1 pool, Func`2 socketFactory, TimeSpan connectionTimeout, TimeSpan readTimeout, TimeSpan writeTimeout)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateFrameHandler(AmqpTcpEndpoint endpoint)\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   --- End of inner exception stack trace ---\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)\r\n   at RabbitMQ.Client.ConnectionFactory.CreateConnection(IList`1 hostnames, String clientProvidedName)\r\n   at MassTransit.RabbitMqTransport.ConnectionContextFactory.CreateConnection(ISupervisor supervisor) in /_/src/Transports/MassTransit.RabbitMqTransport/RabbitMqTransport/ConnectionContextFactory.cs:line 86","InputAddress":"rabbitmq://localhost/","SourceContext":"MassTransit","Application":"auth-service","ExceptionDetail":{"HResult":-2146232800,"Message":"None of the specified endpoints were reachable","Source":"RabbitMQ.Client","TargetSite":"RabbitMQ.Client.IConnection CreateConnection(RabbitMQ.Client.IEndpointResolver, System.String)","InnerException":{"Type":"System.AggregateException","HResult":-2146233088,"Message":"One or more errors occurred. (Connection failed)","Source":"RabbitMQ.Client","TargetSite":"T SelectOne[T](RabbitMQ.Client.IEndpointResolver, System.Func`2[RabbitMQ.Client.AmqpTcpEndpoint,T])","InnerException":{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"},"InnerExceptions":[{"HResult":-2146233088,"Message":"Connection failed","Source":"RabbitMQ.Client","TargetSite":"Void ConnectOrFail(RabbitMQ.Client.ITcpClient, RabbitMQ.Client.AmqpTcpEndpoint, System.TimeSpan)","InnerException":{"Type":"System.Net.Sockets.SocketException","HResult":-2147467259,"Message":"No connection could be made because the target machine actively refused it.","Source":"System.Net.Sockets","TargetSite":"Void ThrowException(System.Net.Sockets.SocketError, System.Threading.CancellationToken)","SocketErrorCode":"ConnectionRefused","SocketErrorCodeMessage":"The remote host is actively refusing a connection."},"Type":"RabbitMQ.Client.Exceptions.ConnectFailureException"}]},"Type":"RabbitMQ.Client.Exceptions.BrokerUnreachableException"}}
